language: php

matrix:
  include:
    - php: 7.4
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.4
    - php: 8.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 8.1

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install:
  - composer update $COMPOSER_FLAGS --no-interaction

script:
  - vendor/bin/phpunit lib


